# Generated by Django 3.0.6 on 2020-05-09 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogspost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment', models.BooleanField()),
                ('U_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogspost.User')),
            ],
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
