# Generated by Django 3.0.6 on 2020-05-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogspost', '0002_auto_20200509_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='sentiment',
            field=models.IntegerField(),
        ),
    ]
