# Generated by Django 3.0.6 on 2020-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogspost', '0004_auto_20200511_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
