# Generated by Django 3.0.6 on 2020-06-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogspost', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
